version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - website.network

  stevenberrisford.com:
    image: stevenb1996/stevenberrisford.com:v1.0.0
    networks:
      - website.network
    expose:
      - "49152"

networks:
  website.network:
    driver: bridge 