version: '3.8'

services:
  ionos.webserver.conf:
    image: stevenb1996/ionos.webserver.conf:v1.0.5
    networks:
      - website.network
    ports:
      - "80:80"
      - "8080:8080"
      - "443":"443"
      - "8443":"8443"

  stevenberrisford:
    image: stevenb1996/stevenberrisford.com:v1.0.6
    networks:
      - website.network
    expose:
      - "49152"

networks:
  website.network:
    driver: bridge 